name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch host ip
      run: echo $(curl ifconfig.me)
    - name: Build the Docker image
      run: docker build -t vamseedocker243/nodejs-app .
    - name: login to dockerhub
      run: docker login -u vamseedocker243 -p @GODwill43 
    - name: push image
      run: docker push vamseedocker243/nodejs-app
    
