name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch host ip
      run: echo $(curl ifconfig.me)
    - name: Build the Docker image
      run: docker build -t node-img .
    - name: Run docker container
      run: docker run -d -p 4000:3000 node-img
